import { NextRequest, NextResponse } from "next/server"
import { z, ZodError } from "zod"
import { createClient } from "@/lib/supabase/server"
import { getCandidateProfile } from "@/lib/supabase/candidate-profile"
import { renderMarkdownResumeToHtml } from "@/lib/ai/markdown-converter"
import { generatePDFFromHTML } from "@/lib/ai/pdf-generator"
import type { ResumeTemplate } from "@/lib/ai/resume-html-template"

// ─── Request schema ───────────────────────────────────────────────────────────

const AssembleResumeSchema = z.object({
  fitMarkdown: z.string().min(50, "fitMarkdown too short"),
  language: z.enum(["pt", "en"]).default("pt"),
  jobAnalysisData: z
    .object({
      empresa: z.string().optional(),
      cargo: z.string().optional(),
    })
    .nullable()
    .optional(),
  resumeTemplate: z.enum(["modelo1", "modelo2"]).default("modelo1"),
})

// ─── Header + Education extractor ────────────────────────────────────────────

/**
 * Extracts the header (name + contact) and education section from the general CV markdown.
 * Stops before any of the 4 adaptable sections generated by generate-fit-markdown.
 */
export function extractHeaderAndEducation(fullMarkdown: string, language: "pt" | "en"): string {
  // These section headers mark where the adaptable part begins
  const adaptableSections =
    language === "en"
      ? ["## PROFESSIONAL PROFILE", "## COMPETENCIES", "## RELEVANT PROJECTS", "## CERTIFICATIONS"]
      : ["## PERFIL PROFISSIONAL", "## COMPETÊNCIAS", "## PROJETOS RELEVANTES", "## CERTIFICAÇÕES"]

  let cutPosition = fullMarkdown.length

  for (const header of adaptableSections) {
    const idx = fullMarkdown.indexOf(header)
    if (idx !== -1 && idx < cutPosition) {
      cutPosition = idx
    }
  }

  return fullMarkdown.substring(0, cutPosition).trimEnd()
}

// ─── Handler ──────────────────────────────────────────────────────────────────

/**
 * POST /api/ai/assemble-resume
 *
 * Assembles a complete resume from:
 * 1. Header + Education extracted from the candidate's general CV (curriculo_geral_md)
 * 2. The 4 personalized sections from fitMarkdown (Profile, Competencies, Projects, Certifications)
 *
 * No LLM call — pure concatenation + HTML/PDF rendering.
 * Designed for the "Add Vaga" modal flow where fitMarkdown already exists from generate-fit-markdown.
 */
export async function POST(req: NextRequest): Promise<NextResponse> {
  const startTime = Date.now()

  try {
    let body: unknown
    try {
      body = await req.json()
    } catch {
      return NextResponse.json({ success: false, error: "Invalid JSON body" }, { status: 400 })
    }

    const { fitMarkdown, language, jobAnalysisData, resumeTemplate } = AssembleResumeSchema.parse(body)

    const supabase = await createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()
    const userId = user?.id

    const candidateProfile = await getCandidateProfile(userId)

    const baseMarkdown =
      language === "en"
        ? candidateProfile.curriculo_geral_md_en?.trim() || candidateProfile.curriculo_geral_md?.trim()
        : candidateProfile.curriculo_geral_md?.trim()

    if (!baseMarkdown) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Currículo geral não encontrado. Configure seu perfil em Configurações > Perfil antes de gerar o currículo.",
        },
        { status: 400 }
      )
    }

    // Extract the static part (header + education) from the general CV
    const headerAndEducation = extractHeaderAndEducation(baseMarkdown, language)

    // Assemble: static header/education + personalized 4 sections
    const fullMarkdown = `${headerAndEducation}\n\n${fitMarkdown}`.trim()

    // Convert markdown → HTML → PDF
    const html = await renderMarkdownResumeToHtml(fullMarkdown, resumeTemplate as ResumeTemplate, language)
    const pdfBuffer = await generatePDFFromHTML(html)
    const pdfBase64 = pdfBuffer.toString("base64")

    const empresa = jobAnalysisData?.empresa || "vaga"
    const cargo = jobAnalysisData?.cargo?.toLowerCase().replace(/\s+/g, "-") || "curriculo"
    const filename = `cv-${cargo}-${empresa.toLowerCase().replace(/\s+/g, "-")}-${language}.pdf`

    const duration = Date.now() - startTime
    console.log(`[assemble-resume] ✅ Done (${duration}ms, ${language})`)

    return NextResponse.json({
      success: true,
      data: {
        markdown: fullMarkdown,
        html,
        pdfBase64,
        filename,
      },
      metadata: { duration },
    })
  } catch (error: unknown) {
    const duration = Date.now() - startTime
    const errorMessage = error instanceof Error ? error.message : String(error)
    console.error(`[assemble-resume] ❌ Error (${duration}ms):`, errorMessage)

    if (error instanceof ZodError) {
      return NextResponse.json({ success: false, error: "Invalid request data", details: error.errors }, { status: 400 })
    }

    return NextResponse.json({ success: false, error: errorMessage }, { status: 500 })
  }
}
